#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HareAndHounds.Resource", IsApplication=true)]

namespace HareAndHounds
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_in_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_in_up = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_out_down = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_out_left = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_out_right = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_out_up = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int btn_bg_color = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int btn_bg_color_blue = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int btn_bg_shadow_color = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int btn_bg_shadow_color_blue = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int quest_color = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int xam_blue = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int xam_dark_blue = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int xam_gray = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int xam_green = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int xam_light_gray = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int xam_medium_blue = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int xam_purple = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int place_map1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int place_map2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int place_map3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int place_map4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int place_map5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int place_map6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ripple_background = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int background = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int button_continue = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int button_play = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int main_image = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int main_text = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int map = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int map_scroll = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Place = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
